/*
 * BuscadorDeTipoDeLogradouro.java
 *
 * Created on 15/02/2012, 15:43:50
 */

package com.ic.projects.laudoecia.control.autocompletar;

import com.lib.icontrol.autocompletar.AutoCompletarUtils;
import com.lib.icontrol.autocompletar.C_AutoCompletarString;
import java.util.ArrayList;
import java.util.List;

/**
 * @author Danilo Brito <danilobrito@instrumentalcientifico.com.br>
 */
public class BuscadorDeTipoDeLogradouro extends C_AutoCompletarString
{

    private List<String> lista = getLista();

    @Override
    public List<Object[]> buscarCandidatos (String textoDaBusca)
    {
        return AutoCompletarUtils.converterLista(
                AutoCompletarUtils.buscarNaListaDesordenada(lista, textoDaBusca));
    }

    private List<String> getLista ()
    {
        List<String> result = new ArrayList<>();
        result.add("RUA");
        result.add("AVENIDA");
        result.add("ALAMEDA");
        result.add("PRAÇA");
        result.add("TRAVESSA");
        result.add("10ª RUA");
        result.add("10ª TRAVESSA");
        result.add("11ª RUA");
        result.add("11ª TRAVESSA");
        result.add("12ª RUA");
        result.add("12ª TRAVESSA");
        result.add("13ª TRAVESSA");
        result.add("14ª TRAVESSA");
        result.add("15ª TRAVESSA");
        result.add("16ª TRAVESSA");
        result.add("1ª AVENIDA");
        result.add("1ª PARALELA");
        result.add("1ª RUA");
        result.add("1ª SUBIDA");
        result.add("1ª TRAVESSA");
        result.add("1ª TRAVESSA DA RODOVIA");
        result.add("1ª VILA");
        result.add("1º ALTO");
        result.add("1º BECO");
        result.add("2ª AVENIDA");
        result.add("2ª PARALELA");
        result.add("2ª RUA");
        result.add("2ª SUBIDA");
        result.add("2ª TRAVESSA");
        result.add("2ª TRAVESSA DA RODOVIA");
        result.add("2ª VILA");
        result.add("2º ALTO");
        result.add("2º BECO");
        result.add("3ª AVENIDA");
        result.add("3ª LADEIRA");
        result.add("3ª PARALELA");
        result.add("3ª RUA");
        result.add("3ª SUBIDA");
        result.add("3ª TRAVESSA");
        result.add("3ª VILA");
        result.add("3º ALTO");
        result.add("3º BECO");
        result.add("4ª AVENIDA");
        result.add("4ª PARALELA");
        result.add("4ª RUA");
        result.add("4ª SUBIDA");
        result.add("4ª TRAVESSA");
        result.add("4ª VILA");
        result.add("5ª AVENIDA");
        result.add("5ª RUA");
        result.add("5ª SUBIDA");
        result.add("5ª TRAVESSA");
        result.add("5ª VILA");
        result.add("6ª AVENIDA");
        result.add("6ª RUA");
        result.add("6ª SUBIDA");
        result.add("6ª TRAVESSA");
        result.add("7ª RUA");
        result.add("7ª TRAVESSA");
        result.add("8ª RUA");
        result.add("8ª TRAVESSA");
        result.add("9ª RUA");
        result.add("9ª TRAVESSA");
        result.add("ACAMPAMENTO");
        result.add("ACESSO");
        result.add("ADRO");
        result.add("AEROPORTO");
        result.add("ALTO");
        result.add("ANTIGA ESTRADA");
        result.add("AOS");
        result.add("ÁREA");
        result.add("ÁREA ESPECIAL");
        result.add("ARTÉRIA");
        result.add("ATALHO");
        result.add("AVENIDA CONTORNO");
        result.add("AVENIDA MARGINAL");
        result.add("AVENIDA MARGINAL DIREITA");
        result.add("AVENIDA MARGINAL ESQUERDA");
        result.add("AVENIDA VELHA");
        result.add("BAIXA");
        result.add("BALÃO");
        result.add("BECO");
        result.add("BELVEDERE");
        result.add("BLOCO");
        result.add("BOSQUE");
        result.add("BOULEVARD");
        result.add("BULEVAR");
        result.add("BURACO");
        result.add("C");
        result.add("CAIS");
        result.add("CALÇADA");
        result.add("CAMINHO");
        result.add("CAMPO");
        result.add("CAMPUS");
        result.add("CANAL");
        result.add("CENTRO");
        result.add("CHÁCARA");
        result.add("CICLOVIA");
        result.add("CIRCULAR");
        result.add("CNB");
        result.add("COLÔNIA");
        result.add("COMPLEXO VIÁRIO");
        result.add("COMUNIDADE");
        result.add("CONDOMÍNIO");
        result.add("CONJUNTO");
        result.add("CONJUNTO MUTIRÃO");
        result.add("CONTORNO");
        result.add("CORREDOR");
        result.add("CÓRREGO");
        result.add("CSA");
        result.add("CSB");
        result.add("DESCIDA");
        result.add("DESVIO");
        result.add("DISTRITO");
        result.add("EIXO INDUSTRIAL");
        result.add("ELEVADA");
        result.add("ENTRADA PARTICULAR");
        result.add("ENTRE QUADRA");
        result.add("EPAC");
        result.add("EQ");
        result.add("ESCADA");
        result.add("ESCADARIA");
        result.add("ESPLANADA");
        result.add("ESTAÇÃO");
        result.add("ESTACIONAMENTO");
        result.add("ESTÁDIO");
        result.add("ESTRADA");
        result.add("ESTRADA DE LIGAÇÃO");
        result.add("ESTRADA DE SERVIDÃO");
        result.add("ESTRADA ESTADUAL");
        result.add("ESTRADA INTERMUNICIPAL");
        result.add("ESTRADA MUNICIPAL");
        result.add("ESTRADA PARTICULAR");
        result.add("ESTRADA VELHA");
        result.add("ESTRADA VICINAL");
        result.add("FAVELA");
        result.add("FAZENDA");
        result.add("FEIRA");
        result.add("FERROVIA");
        result.add("FONTE");
        result.add("FORTE");
        result.add("GALERIA");
        result.add("GRANJA");
        result.add("ILHA");
        result.add("JARDIM");
        result.add("JARDINETE");
        result.add("LADEIRA");
        result.add("LAGO");
        result.add("LAGOA");
        result.add("LARGO");
        result.add("LOTEAMENTO");
        result.add("MARGEM");
        result.add("MARINA");
        result.add("MÓDULO");
        result.add("MONTE");
        result.add("MORRO");
        result.add("NÚCLEO");
        result.add("NÚCLEO RURAL");
        result.add("PARADA");
        result.add("PARALELA");
        result.add("PARQUE");
        result.add("PARQUE MUNICIPAL");
        result.add("PARQUE RESIDENCIAL");
        result.add("PASSAGEM");
        result.add("PASSAGEM DE PEDESTRES");
        result.add("PASSAGEM SUBTERRÂNEA");
        result.add("PASSARELA");
        result.add("PASSEIO");
        result.add("PASSEIO PÚBLICO");
        result.add("PÁTIO");
        result.add("PONTA");
        result.add("PONTE");
        result.add("PORTO");
        result.add("PRAÇA DE ESPORTES");
        result.add("PRAIA");
        result.add("PROLONGAMENTO");
        result.add("QE");
        result.add("QI");
        result.add("QN");
        result.add("QNB");
        result.add("QNG");
        result.add("QS");
        result.add("QUADRA");
        result.add("QUINTA");
        result.add("RAMAL");
        result.add("RAMPA");
        result.add("RECANTO");
        result.add("RESIDENCIAL");
        result.add("RETA");
        result.add("RETIRO");
        result.add("RETORNO");
        result.add("RODO ANEL");
        result.add("RODOVIA");
        result.add("ROTATÓRIA");
        result.add("RÓTULA");
        result.add("RUA DE LIGAÇÃO");
        result.add("RUA DE PEDESTRE");
        result.add("RUA PARTICULAR");
        result.add("RUA PRINCIPAL");
        result.add("RUA VELHA");
        result.add("SAFS");
        result.add("SAI");
        result.add("SAUN");
        result.add("SAUS");
        result.add("SBN");
        result.add("SBS");
        result.add("SCC");
        result.add("SCEN");
        result.add("SCN");
        result.add("SCRN");
        result.add("SCS");
        result.add("SCTN");
        result.add("SDN");
        result.add("SDS");
        result.add("SEN");
        result.add("SEPN");
        result.add("SEPS");
        result.add("SERVIDÃO");
        result.add("SES");
        result.add("SETOR");
        result.add("SGAN");
        result.add("SGAS");
        result.add("SGCV");
        result.add("SGON");
        result.add("SH");
        result.add("SHIS");
        result.add("SHLN");
        result.add("SHLS");
        result.add("SHN");
        result.add("SHS");
        result.add("SIA");
        result.add("SIG");
        result.add("SÍTIO");
        result.add("SMAN");
        result.add("SMAS");
        result.add("SMHN");
        result.add("SMHS");
        result.add("SPO");
        result.add("SPP");
        result.add("SRTVN");
        result.add("SRTVS");
        result.add("STN");
        result.add("SUBIDA");
        result.add("TERMINAL");
        result.add("TRAVESSA PARTICULAR");
        result.add("TRECHO");
        result.add("TREVO");
        result.add("TÚNEL");
        result.add("UNIDADE");
        result.add("VALA");
        result.add("VALE");
        result.add("VEREDA");
        result.add("VIA");
        result.add("VIA COLETORA");
        result.add("VIA COSTEIRA");
        result.add("VIA DE ACESSO");
        result.add("VIA DE PEDESTRE");
        result.add("VIA DE PEDESTRES");
        result.add("VIA EXPRESSA");
        result.add("VIA LITORANEA");
        result.add("VIA LOCAL");
        result.add("VIADUTO");
        result.add("VIELA");
        result.add("VILA");
        result.add("ZIGUE-ZAGUE");
        return result;
    }

}
